### ISSUE TITLE
[BUG] App crashes when changing weapons on a Hertic Astartes Berserker Champion

### ISSUE THREAD

**Issue by DevJonny** [KTManager/KTManagerApp#108]
*Describe the bug*: 
App crashes when attempting to change weapons for Heretic Astartes Berserker Champion

*To Reproduce*
1. Create a Heretic Astartes Team and add a Berserker Champion to the list
2. Click on the Berserker Champion
3. Click on Change Weapons 

*Expected behavior: *
the app should load the available weapons and associated points.

Smartphone (please complete the following information):
- Device: Pixel 3xl, iPad and Bluestacks
- OS: Android v.10 and IOS 13

**Comment by lacombet** [comment]
This is a duplicate of #93 ;)

**Comment by DevJonny** [comment]
Closing as dupe
