### ISSUE TITLE
Fix System.InvalidOperationException in /Users/jonny/code/KTManagerApp/KillTeam/Services/RulesImporter.cs line 37

### ISSUE THREAD

**Issue by lacombet** [KTManager/KTManagerApp#20]
### Stacktrace ###

KillTeam.Services.RulesImporter.ImportType[T] (Microsoft.EntityFrameworkCore.DbSet`1[TEntity] dbSet, System.Collections.Generic.IReadOnlyDictionary`2[TKey,TValue] rules, System.String type, System.Func`3[T1,T2,TResult] mutator) [0x000aa] in /Users/jonny/code/KTManagerApp/KillTeam/Services/RulesImporter.cs:37;KillTeam.Services

KillTeam.Services.RulesImporter.ImportJSON (KillTeam.Services.IKTRulesContext db, KillTeam.Services.RulesProviders.RulesProvider rulesProvider) [0x0017c] in /Users/jonny/code/KTManagerApp/KillTeam/Services/RulesImporter.cs:93;KillTeam.Services

KillTeam.Services.KTRulesContext.ImportRules (KillTeam.Services.RulesProviders.RulesProvider provider) [0x00001] in /Users/jonny/code/KTManagerApp/KillTeam/Services/KTRulesContext.cs:34;KillTeam.Services

KillTeam.Services.DBUpdater.GetUpdatedContext () [0x00043] in /Users/jonny/code/KTManagerApp/KillTeam/Services/DBUpdater.cs:59;KillTeam.Services

KillTeam.Services.KTContext+<>c.<.cctor>b__3_0 () [0x00000] in /Users/jonny/code/KTManagerApp/KillTeam/Services/KTContext.cs:19;KillTeam.Services.KTContext+<>c

KillTeam.Services.KTContext.get_Db () [0x00000] in /Users/jonny/code/KTManagerApp/KillTeam/Services/KTContext.cs:14;KillTeam.Services

KillTeam.ViewModels.ListEquipesViewModel.UpdateListItems () [0x00023] in /Users/jonny/code/KTManagerApp/KillTeam/ViewModels/ListEquipesViewModel.cs:124;KillTeam.ViewModels

KillTeam.ViewModels.ListEquipesViewModel.Refresh () [0x00094] in /Users/jonny/code/KTManagerApp/KillTeam/ViewModels/ListEquipesViewModel.cs:94;KillTeam.ViewModels

KillTeam.Views.ListEquipesPage.OnAppearing () [0x00044] in /Users/jonny/code/KTManagerApp/KillTeam/Views/ListEquipesPage.xaml.cs:28;KillTeam.Views

KillTeam.iOS.Application.Main (System.String[] args) [0x00001] in /Users/jonny/code/KTManagerApp/KillTeam.iOS/Main.cs:12;KillTeam.iOS

### Reason ###

System.InvalidOperationException

### Link to App Center ###

* [https://appcenter.ms/users/tlacombe/apps/KillTeam-Manager-iOS/crashes/errors/4137912607u](https://appcenter.ms/users/tlacombe/apps/KillTeam-Manager-iOS/crashes/errors/4137912607u)

**Comment by DevJonny** [comment]
Me testing locally.
