### ISSUE TITLE
[BUG] Kill Teams are deleted on iOS with new Database upgrade

### ISSUE THREAD

**Issue by LordFckHelmchen** [KTManager/KTManagerApp#39]
**Describe the bug**
Despite the changelog stating that the team deletion is fixed, my teams were deleted when I upgraded to the new version.

**To Reproduce**
Prerequisites: iOS 12.4.5, iPhone 6 (MQ3D2ZD/A) + KT Manager v2.0.1 installed
1. Have 2 Kill Teams (Orks & DG)
2. Install update to 2.1.4
3. Observe: No Kill Teams in list

**Expected behavior**
Old Kill Teams are still accessible & are updated to the new rules.

**Comment by lacombet** [comment]
This has been addressed and fixed in 2.1.5.
