### ISSUE TITLE
In Game view rewriting

### ISSUE THREAD

**Issue by lacombet** [KTManager/KTManagerApp#67]
- [ ] Display members list
- [ ] Display first / selected member sheet
- [ ] Change Flesh Wounds
- [ ] Change Experience

**Comment by Bnorus** [comment]
@lacombet add to the list that Dark Theme needs to be check with in-game mode, 
![image](https://user-images.githubusercontent.com/5378304/77292323-085bcd00-6d1b-11ea-8316-a3a990efc06b.png)

**Comment by lacombet** [comment]
Hi Bnorus,

Nope, I'll actually create a new issue for that.
All the "View rewriting" issues are enhancements and have no deadline.

This is a bug, which must be corrected as soon as possible. It must not wait for the redesign of the UI.
